---
  - name: Install AX.25 packages
    apt:
      state: present
      name:
        - ax25-tools
        - ax25-apps

  - name: Ensure netrom is loaded on boot
    lineinfile:
      path: /etc/modules
      line: netrom

  - name: load netrom module
    modprobe:
      name: netrom
      state: present
  
  - name: install systemd unit files
    copy:
      dest: "/etc/systemd/system/{{item}}"
      src: "{{item}}"
    register: unit_files
    with_items:
      - kiss-tnc@.service
      - nrattach@.service
      - netromd.service
      - nodesave.service

  - name: Create TNC instance configuration directories
    file:
      state: directory
      path: "/etc/systemd/system/kiss-tnc@{{item}}.service.d"
    with_items: "{{ax_25_ports}}"

  - name: Configure TNC instances
    template:
      src: kiss-tnc-override.j2
      dest: "/etc/systemd/system/kiss-tnc@{{item}}.service.d/override.conf"
    with_items: "{{ax_25_ports}}"
    when: ax_25_ports[item].type == 'kiss'
    register: unit_override_files

  - name: reload systemd unit files if necessary
    systemd:
      daemon_reload: true
    when: unit_files.changed or unit_override_files.changed

  - name: Template AX.25 configuration files
    template:
      dest: "/etc/ax25/{{item}}"
      src: "{{item}}.j2"
    with_items:
      - axports
      - nrports
      - nrbroadcast
      - ax25ipd.conf

  - name: Enable services
    systemd:
      name: "{{item}}" 
      enabled: true
    with_items:
      - netromd.service
      - nodesave.service

  - name: Enable netrom ports
    systemd:
      name: "nrattach@{{item}}.service"
      enabled: true
    with_items: "{{nr_ports}}"

  - name: Start TNCs
    systemd: 
      name: "kiss-tnc@{{item}}.service"
      state: started
    with_items: "{{ax_25_ports}}"
    when: ax_25_ports[item].type == 'kiss'
    register: unit_override_files

  - name: Start netrom ports
    systemd:
      name: "nrattach@{{item}}.service"
      state: started
    with_items: "{{nr_ports}}"

  - name: Start netromd
    systemd:
      name: netromd.service
      state: started
